import type { Deployment } from "./types";

export const MOCK_DEPLOYMENTS: Deployment[] = [
  {
    id: "1",
    name: "Staging Environment",
    url: "https://api.dev.example.com",
    type: "agent",
    status: "draft",
    health: "pending",
    attachedCount: 2,
    provider: "Langflow Cloud",
    lastModified: "2026-02-10",
    lastModifiedBy: "Sarah Han",
  },
  {
    id: "2",
    name: "Production Main Deployment",
    url: "https://api.production.example.com",
    type: "agent",
    status: "production",
    health: "healthy",
    attachedCount: 1,
    provider: "Langflow Cloud",
    lastModified: "2026-02-09",
    lastModifiedBy: "Sarah Han",
  },
  {
    id: "3",
    name: "Test Environment A",
    url: "https://api.staging.example.com",
    type: "agent",
    status: "draft",
    health: "healthy",
    attachedCount: 1,
    provider: "watsonx Orchestrate",
    lastModified: "2026-02-08",
    lastModifiedBy: "Sarah Han",
  },
  {
    id: "4",
    name: "Development Instance",
    url: "https://api.dev.example.com",
    type: "mcp",
    status: "draft",
    health: "unhealthy",
    attachedCount: 2,
    provider: "AWS Cloud Deploy",
    lastModified: "2026-02-06",
    lastModifiedBy: "Sarah Han",
  },
];
